force-app/main/default/objects/Expenses_Detail__c/Expenses_Detail__c.object-meta.xml
<CustomObject>
    <label>费用详细</label>
    <nameField>
        <displayFormat>ED-{000000000}</displayFormat>
        <label>名称</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Expenses_Detail__c/fields/Address__c.field-meta.xml
<CustomField>
    <fullName>Address__c</fullName>
    <label>地址</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Expenses_Detail__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <label>金额</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Expenses_Detail__c/fields/Expense_Categories__c.field-meta.xml
<CustomField>
    <fullName>Expense_Categories__c</fullName>
    <label>费用大类</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Expenses_Detail__c/fields/Expense_Projects__c.field-meta.xml
<CustomField>
    <fullName>Expense_Projects__c</fullName>
    <label>费用项目</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Expenses_Detail__c/fields/Pay_Type__c.field-meta.xml
<CustomField>
    <fullName>Pay_Type__c</fullName>
    <label>付款方式</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AP</fullName>
            </value>
            <value>
                <fullName>ER</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Expenses_Detail__c/fields/Payment__c.field-meta.xml
<CustomField>
    <fullName>Payment__c</fullName>
    <label>付款申请</label>
    <referenceTo>Payment_Request__c</referenceTo>
    <relationshipLabel>费用详细</relationshipLabel>
    <relationshipName>Expense_Detail</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Expenses_Detail__c/fields/Payment_Object__c.field-meta.xml
<CustomField>
    <fullName>Payment_Object__c</fullName>
    <label>付款对象</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>HCP/HCO</fullName>
            </value>
            <value>
                <fullName>第三方供应商</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Expenses_Detail__c/fields/Pcc_Code__c.field-meta.xml
<CustomField>
    <fullName>Pcc_Code__c</fullName>
    <label>Pcc Code</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Expenses_Detail__c/fields/Product_Codes__c.field-meta.xml
<CustomField>
    <fullName>Product_Codes__c</fullName>
    <label>产品代码</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Expenses_Detail__c/fields/Vendor_Remark__c.field-meta.xml
<CustomField>
    <fullName>Vendor_Remark__c</fullName>
    <label>Vendor  Remark</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Expenses_Detail__c/fields/VendorID__c.field-meta.xml
<CustomField>
    <fullName>VendorID__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vendor ID</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>费用详细</relationshipLabel>
    <relationshipName>Expense_Detail</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Expenses_Management__c/Expenses_Management__c.object-meta.xml
<CustomObject>
    <label>费用管理</label>
    <nameField>
        <label>费用大类</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Expenses_Management__c/fields/Expenses__c.field-meta.xml
<CustomField>
    <fullName>Expenses__c</fullName>
    <formula>Expenses_Type__c +&apos;_&apos;+ Expenses_TypeEN__c + &apos;_&apos; + Pcc_Code__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>费用类别</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Expenses_Management__c/fields/Pcc_Code__c.field-meta.xml
<CustomField>
    <fullName>Pcc_Code__c</fullName>
    <label>Pcc Code</label>
    <length>200</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product_Code__c/Product_Code__c.object-meta.xml
<CustomObject>
    <label>产品代码</label>
    <nameField>
        <label>产品代码</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/PaymentDetailsController.cls
/**************************************************************************************************
 * Name: PaymentDetailsController
 * Object: Expenses_Detail__c
 * Purpose: for payment details compt
 * Author: zhou
 * Create Date: 2019-9-17
***************************************************************************************************/
public class PaymentDetailsController{
    
    @AuraEnabled
    public Static List<Expenses_Detail__c> doInit(String recordId){
        if(String.isNotBlank(recordId)){
           List<Expenses_Detail__c> edlist = [SELECT Id,Name,Pcc_Code__c,VendorID__c,VendorID__r.Name,Vendor_Remark__c,
                                        Product_Codes__c,Payment_Object__c,Pay_Type__c,Expense_Projects__c,
                                        Payment__c,Address__c,Expense_Categories__c,Amount__c
                                        FROM Expenses_Detail__c WHERE Payment__c =:recordId];
            for(Expenses_Detail__c rcd:edlist){
                if(rcd.Payment_Object__c == '第三方供应商')rcd.Payment_Object__c = 'H3';
            }
            if(edlist.size()>0)return edlist;
        }
        return Null;
    }

    @AuraEnabled
    public Static String getAccounts(String accid){
        
        try{
            return JSON.serialize(new Map<String, Object>{
                'success' => true,
                'data' => [SELECT Id,Name FROM Account WHERE Id = :accid][0]
            });
        }catch(Exception e){
            return JSON.serialize(new Map<String, Object>{
                'success' => false,
                'error' => e.getMessage()
            });
        }
    }
	/*
    @AuraEnabled
    public Static List<Map<String, String>> setProductCodes(){
        List<Map<String, String>> items = new List<Map<String, String>>();
        List<Product_Code__c> codelist = [SELECT Id,Name FROM Product_Code__c];
        Set<String> sets = new Set<String>();
        if(!codelist.isEmpty()){
            for(Product_Code__c rcd:codelist){
                sets.add(rcd.Name);
            }
            if(sets.size()>0){
                for(String str:sets){
                    items.add(new Map<String, String>{'value' => str, 'label' => str});
                }   
            }
        }
        if(!items.isEmpty()) return items;
        return Null;
    }*/

    @AuraEnabled
    public Static List<Map<String, String>> setPayType(){
        List<Map<String, String>> items = new List<Map<String, String>>();
        String[] strlist = Utilities.picklist_values('Expenses_Detail__c','Pay_Type__c');
        if(!strlist.isEmpty()){
            for(String str:strlist){
                items.add(new Map<String, String>{'value' => str, 'label' => str});
            }   
        }
        if(!items.isEmpty()) return items;
        return Null;
    }

    @AuraEnabled
    public Static List<Map<String, String>> setCategories(String cname){
        List<Map<String, String>> items = new List<Map<String, String>>();
        List<Expenses_Management__c> codelist;
        Set<String> sets = new Set<String>();
        if(String.isNotBlank(cname)){
            codelist = [SELECT Id,Name FROM Expenses_Management__c WHERE Expenses__c =:cname];
        }else{
            codelist = [SELECT Id,Name FROM Expenses_Management__c];
        }
        
        if(!codelist.isEmpty()){
            for(Expenses_Management__c rcd:codelist){
                sets.add(rcd.Name);
            }
            if(sets.size() > 0){
                for(String str:sets){
                    items.add(new Map<String, String>{'value' => str, 'label' => str});
                }
            }
        }
        if(!items.isEmpty()) return items;
        return Null;
    }

    @AuraEnabled
    public Static Map<String,List<Map<String, String>>> setProjects(){
        Map<String,List<Map<String, String>>> result = new Map<String,List<Map<String, String>>>();
        Set<String> setItems = new Set<String>();
        Set<String> setitms = new Set<String>();
        List<Expenses_Management__c> items = [SELECT Id,Name FROM Expenses_Management__c];
        if(!items.isEmpty()){
            for(Expenses_Management__c rcd:items){
                setItems.add(rcd.Name);
            }
            if(!setItems.isEmpty()){
                for(String s:setItems){
                    List<Map<String, String>> projitems = new List<Map<String, String>>();
                    List<Expenses_Management__c> projs = [SELECT Id,Expenses__c FROM Expenses_Management__c WHERE Name=:s];
                    if(!projs.isEmpty()){
                        for(Expenses_Management__c em:projs){
                            projitems.add(new Map<String, String>{'value' => em.Expenses__c, 'label' => em.Expenses__c});
                        }
                    }
                    result.put(s,projitems);
                }
            }
        }
        System.debug('result:  '+result);
        return result;
    }

    @AuraEnabled
    public Static List<String> setExpenses(String code){
        List<String> result = new List<String>();
        if(String.isNotBlank(code)){
            try{
                Expenses_Management__c rcd = [SELECT Id,Pcc_Code__c,Name,Expenses__c FROM Expenses_Management__c WHERE Pcc_Code__c =:code limit 1];
                result.add(rcd.Name);
                result.add(rcd.Expenses__c);
                return result;
            }catch(Exception e){System.debug(e.getMessage());}
        }
        return Null;
    }

    @AuraEnabled
    public Static List<Map<String, String>> getProjects(String categories,List<String> arrlist){
        List<Map<String, String>> result = new List<Map<String, String>>();
        Set<String> results = new Set<String>();
        if(String.isNotBlank(categories)){
                List<Expenses_Management__c> emlist = [SELECT Id,Pcc_Code__c,Name,Expenses__c FROM Expenses_Management__c WHERE Name =:categories];
                if(!emlist.isEmpty()){
                    for(Expenses_Management__c rcd:emlist){
                        results.add(rcd.Expenses__c);
                    }
                    if(!arrlist.isEmpty()){
                        for(String str:arrlist){
                            results.add(str);
                        }
                    }
                    if(!results.isEmpty()) {
                        for(String s:results){
                            result.add(new Map<String, String>{'value' => s, 'label' => s});
                        }
                    }
                }
                return result;
        }
        return Null;
    }

    @AuraEnabled
    public Static List<String> setPccCode(String projname){
        List<String> result = new List<String>();
        if(String.isNotBlank(projname)){
            try{
                Expenses_Management__c rcd = [SELECT Id,Name,Pcc_Code__c FROM Expenses_Management__c WHERE Expenses__c =:projname limit 1];
                result.add(rcd.Name);
                result.add(rcd.Pcc_Code__c);
                return result;
            }catch(Exception e){System.debug(e.getCause());}
        }
        return Null;
    }

    @AuraEnabled
    public Static Boolean doSaveMethd(String datas){ 
        if(String.isNotBlank(datas)){
            List<Expenses_Detail__c> items = (List<Expenses_Detail__c>)JSON.deserialize(datas, List<Expenses_Detail__c>.class);
            if(items.size()>0){
                for(Expenses_Detail__c rcd:items){
                    rcd.VendorID__r = NUll;
                    if(rcd.Payment_Object__c == '请选择') rcd.Payment_Object__c = Null;
                    if(rcd.Payment_Object__c == 'H3') rcd.Payment_Object__c = '第三方供应商';
                    if(rcd.Pay_Type__c == '请选择') rcd.Pay_Type__c = Null;
                    if(rcd.Expense_Categories__c == '请选择') rcd.Expense_Categories__c = Null;
                    if(rcd.Expense_Projects__c == '请选择') rcd.Expense_Projects__c = Null;
                }
                try{
                    Database.Upsert(items);
                    return true;
                }catch(Exception e){System.debug(e.getMessage());}
            }
        }
        return false;
    }

    @AuraEnabled
    public Static Boolean doDel(String pid){
        if(String.isNotBlank(pid)){
            try{
                Expenses_Detail__c item = [SELECT Id FROM Expenses_Detail__c WHERE Id =:pid];
                Database.delete(item);
                return true;
            }catch(Exception e){
                System.debug(e.getCause());
            }
        }
        return false;
    }
    
    @AuraEnabled
    public Static Boolean doNew(String recordId){
        Expenses_Detail__c rcd = new Expenses_Detail__c(Payment__c = recordId);
        try{Database.insert(rcd); return true;}catch(Exception e){System.debug(e.getMessage());}
        return false;
    }
}