force-app/main/default/objects/ProcesWorkitem__c/ProcesWorkitem__c.object-meta.xml
<CustomObject>
    <label>ProcesWorkitem</label>
    <nameField>
        <displayFormat>PW-{00000000}</displayFormat>
        <label>No</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ProcesWorkitem__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>客户</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>ProcesWorkitem</relationshipLabel>
    <relationshipName>ProcesWorkitem</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ProcesWorkitem__c/fields/AccountName__c.field-meta.xml
<CustomField>
    <fullName>AccountName__c</fullName>
    <label>客户名称</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ProcesWorkitem__c/fields/ApprovalIdeas__c.field-meta.xml
<CustomField>
    <fullName>ApprovalIdeas__c</fullName>
    <label>批准意见</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/ProcesWorkitem__c/fields/ApprovalName__c.field-meta.xml
<CustomField>
    <fullName>ApprovalName__c</fullName>
    <label>提交人名称</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ProcesWorkitem__c/fields/CurrencyApprover__c.field-meta.xml
<CustomField>
    <fullName>CurrencyApprover__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>提交人</label>
    <referenceTo>User</referenceTo>
    <relationshipName>ProcesWorkitem</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ProcesWorkitem__c/fields/CurrencyName__c.field-meta.xml
<CustomField>
    <fullName>CurrencyName__c</fullName>
    <label>当前审批人</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ProcesWorkitem__c/fields/InstanceId__c.field-meta.xml
<CustomField>
    <fullName>InstanceId__c</fullName>
    <label>实体Id</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ProcesWorkitem__c/fields/IsChecked__c.field-meta.xml
<CustomField>
    <fullName>IsChecked__c</fullName>
    <defaultValue>false</defaultValue>
    <label>是否选择</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ProcesWorkitem__c/fields/submitedDate__c.field-meta.xml
<CustomField>
    <fullName>submitedDate__c</fullName>
    <label>提交日期</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ProcesWorkitem__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>类型</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/MassApprovalProcessController.cls
public class MassApprovalProcessController{
    
	@AuraEnabled
    public static List<ProcesWorkitem__c> getItems(){
        list<ProcesWorkitem__c> records = new list<ProcesWorkitem__c>();
        Set<String> setids = new Set<String>();
        Map<Id,Account> accts = new Map<Id,Account>([Select ID from Account where ApproveStatus__c = '已提交']);
        for(ProcessInstance ins: [Select ID,createdDate from ProcessInstance where TargetObjectId In: accts.keySet()]){
            setids.add(ins.Id);
        }
        for(ProcessInstanceWorkitem item: [Select Id,ActorId,Actor.Name,ProcessInstanceId,ProcessInstance.SubmittedById,
                                           ProcessInstance.TargetObjectId,ProcessInstance.TargetObject.Name,ProcessInstance.createdDate
                                           From ProcessInstanceWorkitem Where ProcessInstanceId In:setids])
        {
            ProcesWorkitem__c p = new ProcesWorkitem__c();
            p.CurrencyApprover__c = item.ProcessInstance.SubmittedById;
            p.ApprovalName__c = [select Id,name from user where id =:item.ProcessInstance.SubmittedById].name;
            p.Account__c = item.ProcessInstance.TargetObjectId;
            p.AccountName__c = item.ProcessInstance.TargetObject.Name;
            p.CurrencyName__c = item.Actor.Name;
            p.IsChecked__c = false;
            p.ApprovalIdeas__c = '';
            p.InstanceId__c = item.Id;
            p.Type__c = 'Account';
            p.submitedDate__c = string.valueOf(Date.today());
            records.add(p);
        }
        return records;
    }
    
    @AuraEnabled
    public static void doApproveMethod(List<ProcesWorkitem__c> data,string myaction){
       
        if(!data.isEmpty()){
            List<ProcesWorkitem__c> records = new List<ProcesWorkitem__c>();
            for(ProcesWorkitem__c item: data){
                if(item.IsChecked__c){
                   Approval.ProcessWorkitemRequest req2 = new Approval.ProcessWorkitemRequest();
                    req2.setComments(item.ApprovalIdeas__c);
                    req2.setAction(myaction);
                    req2.setWorkitemId(item.InstanceId__c);
                    Approval.ProcessResult result2 =  Approval.process(req2);
                }
            }
        }
    }    
}