force-app/main/default/objects/Company_Chop__c/Company_Chop__c.object-meta.xml
<CustomObject>
    <label>Company Chop</label>
    <nameField>
        <displayFormat>CR-{000000000}</displayFormat>
        <label>申请编号</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Company_Chop__c/fields/Apply_Date__c.field-meta.xml
<CustomField>
    <fullName>Apply_Date__c</fullName>
    <defaultValue>TODAY()</defaultValue>
    <label>申请日期</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Company_Chop__c/fields/Apply_Department__c.field-meta.xml
<CustomField>
    <fullName>Apply_Department__c</fullName>
    <formula>$User.Department</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>申请人部门</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Company_Chop__c/fields/Apply_User__c.field-meta.xml
<CustomField>
    <fullName>Apply_User__c</fullName>
    <formula>$User.FirstName + &apos; &apos; +  $User.LastName</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>申请人姓名</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Company_Chop__c/fields/Certification_Doc__c.field-meta.xml
<CustomField>
    <fullName>Certification_Doc__c</fullName>
    <label>证照文件</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Legal_Entity__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>营业执照正副本</fullName>
            </value>
            <value>
                <fullName>法人身份证</fullName>
            </value>
            <value>
                <fullName>开户许可证</fullName>
            </value>
            <value>
                <fullName>一般纳税人资格证书</fullName>
            </value>
            <value>
                <fullName>外汇登记证</fullName>
            </value>
            <value>
                <fullName>外资企业备案证明</fullName>
            </value>
            <value>
                <fullName>医疗器械经营许可证</fullName>
            </value>
            <value>
                <fullName>第二类医疗器械经营备案凭证</fullName>
            </value>
            <value>
                <fullName>药品经营许可证 正副本</fullName>
            </value>
            <value>
                <fullName>GSP证书</fullName>
            </value>
            <value>
                <fullName>进口药品注册证</fullName>
            </value>
            <value>
                <fullName>药品生产许可证</fullName>
            </value>
            <value>
                <fullName>海关登记证</fullName>
            </value>
            <value>
                <fullName>自理报检证</fullName>
            </value>
            <value>
                <fullName>财政登记证</fullName>
            </value>
            <value>
                <fullName>银行开户结算书</fullName>
            </value>
            <value>
                <fullName>回乡证</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Company_Chop__c/fields/Contract_Management__c.field-meta.xml
<CustomField>
    <fullName>Contract_Management__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>关联合同审批单</label>
    <referenceTo>CustomContract__c</referenceTo>
    <relationshipLabel>Company Chop</relationshipLabel>
    <relationshipName>Company_Chop</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Company_Chop__c/fields/Contract_Type__c.field-meta.xml
<CustomField>
    <fullName>Contract_Type__c</fullName>
    <label>合同类型</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>采购相关协议</fullName>
            </value>
            <value>
                <fullName>临床研究相关协议</fullName>
            </value>
            <value>
                <fullName>OEC相关协议</fullName>
            </value>
            <value>
                <fullName>HR相关协议</fullName>
            </value>
            <value>
                <fullName>HIV招标相关协议</fullName>
            </value>
            <value>
                <fullName>商务部相关协议</fullName>
            </value>
            <value>
                <fullName>办公租赁协议</fullName>
            </value>
            <value>
                <fullName>质量部相关协议</fullName>
            </value>
            <value>
                <fullName>医学相关协议</fullName>
            </value>
            <value>
                <fullName>注册部相关协议</fullName>
            </value>
            <value>
                <fullName>MA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Company_Chop__c/fields/Contract_Types__c.field-meta.xml
<CustomField>
    <fullName>Contract_Types__c</fullName>
    <label>合同分类</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Contract_Type__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>框架协议/补充或修改协议</fullName>
            </value>
            <value>
                <fullName>未使用或修改艾伯维模板的采购协议</fullName>
            </value>
            <value>
                <fullName>工作说明书(SOW)</fullName>
            </value>
            <value>
                <fullName>Local Review</fullName>
            </value>
            <value>
                <fullName>Global Review</fullName>
            </value>
            <value>
                <fullName>保密协议</fullName>
            </value>
            <value>
                <fullName>捐赠协议</fullName>
            </value>
            <value>
                <fullName>赞助协议</fullName>
            </value>
            <value>
                <fullName>参会协议</fullName>
            </value>
            <value>
                <fullName>研究资助协议</fullName>
            </value>
            <value>
                <fullName>员工劳动合同/劳务解除合同</fullName>
            </value>
            <value>
                <fullName>其他与政府合同</fullName>
            </value>
            <value>
                <fullName>其他与HR部门相关或发起的协议</fullName>
            </value>
            <value>
                <fullName>招标相关-标书</fullName>
            </value>
            <value>
                <fullName>招标相关-药品配送协议</fullName>
            </value>
            <value>
                <fullName>招标相关-中标服务费支付协议</fullName>
            </value>
            <value>
                <fullName>招标相关-采购合同</fullName>
            </value>
            <value>
                <fullName>经销商相关合作协议（使用公司模板）</fullName>
            </value>
            <value>
                <fullName>销售合同</fullName>
            </value>
            <value>
                <fullName>艾伯维分公司</fullName>
            </value>
            <value>
                <fullName>租赁式服务办公室</fullName>
            </value>
            <value>
                <fullName>质量保证协议</fullName>
            </value>
            <value>
                <fullName>药物警戒协议</fullName>
            </value>
            <value>
                <fullName>临床研究协议</fullName>
            </value>
            <value>
                <fullName>委托检验合同</fullName>
            </value>
            <value>
                <fullName>其他</fullName>
            </value>
            <value>
                <fullName>谈判协议，与政府相关协议</fullName>
            </value>
            <value>
                <fullName>药物经济学合同(供应商模板)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Company_Chop__c/fields/Files_Content__c.field-meta.xml
<CustomField>
    <fullName>Files_Content__c</fullName>
    <label>文件内容</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Files_Types__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>在职证明/薪资证明</fullName>
            </value>
            <value>
                <fullName>劳动手册/退工单</fullName>
            </value>
            <value>
                <fullName>税单/完税证明</fullName>
            </value>
            <value>
                <fullName>居住证申请文件</fullName>
            </value>
            <value>
                <fullName>外籍员工居留许可/工作签证申请文件</fullName>
            </value>
            <value>
                <fullName>员工社保/公积金相关文件</fullName>
            </value>
            <value>
                <fullName>ESPP相关文件</fullName>
            </value>
            <value>
                <fullName>公司信用卡申请</fullName>
            </value>
            <value>
                <fullName>公司税务相关文件</fullName>
            </value>
            <value>
                <fullName>询证函</fullName>
            </value>
            <value>
                <fullName>注册申请表</fullName>
            </value>
            <value>
                <fullName>注册申请资料封面</fullName>
            </value>
            <value>
                <fullName>公文、申请函、企业标准、COA</fullName>
            </value>
            <value>
                <fullName>自查表</fullName>
            </value>
            <value>
                <fullName>临床试验方案、临床试验总结报告</fullName>
            </value>
            <value>
                <fullName>经销商授权书</fullName>
            </value>
            <value>
                <fullName>配送委托书</fullName>
            </value>
            <value>
                <fullName>招投标文件</fullName>
            </value>
            <value>
                <fullName>价格相关文件</fullName>
            </value>
            <value>
                <fullName>产品资料</fullName>
            </value>
            <value>
                <fullName>法人委托书</fullName>
            </value>
            <value>
                <fullName>进药资料</fullName>
            </value>
            <value>
                <fullName>授权委托书</fullName>
            </value>
            <value>
                <fullName>律师函</fullName>
            </value>
            <value>
                <fullName>声明</fullName>
            </value>
            <value>
                <fullName>授权书</fullName>
            </value>
            <value>
                <fullName>准入/谈判相关申请函/沟通函/说明函</fullName>
            </value>
            <value>
                <fullName>其他需Legal审阅文件</fullName>
            </value>
            <value>
                <fullName>医疗器械年度自查报告</fullName>
            </value>
            <value>
                <fullName>医疗器械检查记录（日常监督检查、专项检查以及飞行检查等）</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Company_Chop__c/fields/Files_Type__c.field-meta.xml
<CustomField>
    <fullName>Files_Type__c</fullName>
    <label>文件类型</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>证照</fullName>
            </value>
            <value>
                <fullName>合同</fullName>
            </value>
            <value>
                <fullName>其他</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Company_Chop__c/fields/Files_Types__c.field-meta.xml
<CustomField>
    <fullName>Files_Types__c</fullName>
    <label>文件大类</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>HR相关文件</fullName>
            </value>
            <value>
                <fullName>财务相关文件</fullName>
            </value>
            <value>
                <fullName>RA注册相关文件</fullName>
            </value>
            <value>
                <fullName>Trade相关招标资料</fullName>
            </value>
            <value>
                <fullName>BU相关文件</fullName>
            </value>
            <value>
                <fullName>Legal相关文件</fullName>
            </value>
            <value>
                <fullName>GSP相关文件</fullName>
            </value>
            <value>
                <fullName>市场准入相关文件</fullName>
            </value>
            <value>
                <fullName>报关相关文件</fullName>
            </value>
            <value>
                <fullName>临床研究相关文件</fullName>
            </value>
            <value>
                <fullName>VISA相关文件</fullName>
            </value>
            <value>
                <fullName>行政相关文件</fullName>
            </value>
            <value>
                <fullName>PA相关文件</fullName>
            </value>
            <value>
                <fullName>超过系统容量的超大文件</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Company_Chop__c/fields/Legal_Entity__c.field-meta.xml
<CustomField>
    <fullName>Legal_Entity__c</fullName>
    <label>法律实体</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>艾伯维医药贸易(上海)有限公司</fullName>
            </value>
            <value>
                <fullName>北京分公司</fullName>
            </value>
            <value>
                <fullName>广州分公司</fullName>
            </value>
            <value>
                <fullName>杭州分公司</fullName>
            </value>
            <value>
                <fullName>成都分公司</fullName>
            </value>
            <value>
                <fullName>静安分公司</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Company_Chop__c/fields/Remark__c.field-meta.xml
<CustomField>
    <fullName>Remark__c</fullName>
    <label>备注</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Company_Chop__c/fields/Seal_Type__c.field-meta.xml
<CustomField>
    <fullName>Seal_Type__c</fullName>
    <label>盖章类型</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>公章</fullName>
            </value>
            <value>
                <fullName>法人章</fullName>
            </value>
            <value>
                <fullName>合同章</fullName>
            </value>
            <value>
                <fullName>财务专用章</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CustomContract__c/CustomContract__c.object-meta.xml
<CustomObject>
    <label>合同</label>
    <nameField>
        <label>合同名称</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/ChopRequestController.cls
/**************************************************************************************************
 * Name: ChopRequestController
 * Object: Chop_Request
 * Author: zhou
 * Create Date: 2019-9-11
***************************************************************************************************/
public class ChopRequestController{

    @AuraEnabled
    public Static Company_Chop__c doInitMethod(String rid){
      try{
        Company_Chop__c rcd = [SELECT Id,Name,Contract_Management__c,Contract_Management__r.Name,
        Contract_Types__c,Contract_Type__c,Remark__c,Files_Content__c,
        Files_Types__c,Files_Type__c,Legal_Entity__c,Apply_User__c,
        Apply_Department__c,Apply_Date__c,Seal_Type__c,Certification_Doc__c
        FROM Company_Chop__c WHERE Id =:rid];
        return rcd;
      }catch(Exception e){System.debug(e.getMessage());}
      return Null;
    }   

    @AuraEnabled
    public static String getContracts(String contid)
    {
        try{
            return JSON.serialize(new Map<String, Object>{
                'success' => true,
                'data' => [SELECT Id,Name FROM CustomContract__c WHERE Id = :contid][0]
            });
        }catch(Exception e){
            return JSON.serialize(new Map<String, Object>{
                'success' => false,
                'error' => e.getMessage()
            });
        }
    }

    @AuraEnabled
    public Static Boolean doSaveMethod(String reqt){
       Company_Chop__c item = (Company_Chop__c)JSON.deserialize(reqt, Company_Chop__c.class);
       try{
           Database.Update(item);
           return true;
       }catch(Exception e){System.debug(e.getMessage());}
       return false;
    }  
}