force-app/main/default/objects/Company_Chop__c/Company_Chop__c.object-meta.xml
<CustomObject>
    <label>Company Chop</label>
    <nameField>
        <displayFormat>CR-{000000000}</displayFormat>
        <label>申请编号</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Company_Chop__c/fields/Approver1__c.field-meta.xml
<CustomField>
    <fullName>Approver1__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Approver1</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Company_Chop</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Company_Chop__c/fields/Approver2__c.field-meta.xml
<CustomField>
    <fullName>Approver2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Approver2</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Company_Chop1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Company_Chop__c/fields/Approver3__c.field-meta.xml
<CustomField>
    <fullName>Approver3__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Approver3</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Company_Chop2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Company_Chop__c/fields/Approver4__c.field-meta.xml
<CustomField>
    <fullName>Approver4__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Approver4</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Company_Chop3</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Company_Chop__c/fields/Certification_Doc__c.field-meta.xml
<CustomField>
    <fullName>Certification_Doc__c</fullName>
    <label>证照文件</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Legal_Entity__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>营业执照正副本</fullName>
            </value>
            <value>
                <fullName>法人身份证</fullName>
            </value>
            <value>
                <fullName>开户许可证</fullName>
            </value>
            <value>
                <fullName>一般纳税人资格证书</fullName>
            </value>
            <value>
                <fullName>外汇登记证</fullName>
            </value>
            <value>
                <fullName>外资企业备案证明</fullName>
            </value>
            <value>
                <fullName>医疗器械经营许可证</fullName>
            </value>
            <value>
                <fullName>第二类医疗器械经营备案凭证</fullName>
            </value>
            <value>
                <fullName>药品经营许可证 正副本</fullName>
            </value>
            <value>
                <fullName>GSP证书</fullName>
            </value>
            <value>
                <fullName>进口药品注册证</fullName>
            </value>
            <value>
                <fullName>药品生产许可证</fullName>
            </value>
            <value>
                <fullName>海关登记证</fullName>
            </value>
            <value>
                <fullName>自理报检证</fullName>
            </value>
            <value>
                <fullName>财政登记证</fullName>
            </value>
            <value>
                <fullName>银行开户结算书</fullName>
            </value>
            <value>
                <fullName>回乡证</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Company_Chop__c/fields/Contract_Type__c.field-meta.xml
<CustomField>
    <fullName>Contract_Type__c</fullName>
    <label>合同类型</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>采购相关协议</fullName>
            </value>
            <value>
                <fullName>临床研究相关协议</fullName>
            </value>
            <value>
                <fullName>OEC相关协议</fullName>
            </value>
            <value>
                <fullName>HR相关协议</fullName>
            </value>
            <value>
                <fullName>HIV招标相关协议</fullName>
            </value>
            <value>
                <fullName>商务部相关协议</fullName>
            </value>
            <value>
                <fullName>办公租赁协议</fullName>
            </value>
            <value>
                <fullName>质量部相关协议</fullName>
            </value>
            <value>
                <fullName>医学相关协议</fullName>
            </value>
            <value>
                <fullName>注册部相关协议</fullName>
            </value>
            <value>
                <fullName>MA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Company_Chop__c/fields/Contract_Types__c.field-meta.xml
<CustomField>
    <fullName>Contract_Types__c</fullName>
    <label>合同分类</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Contract_Type__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>框架协议/补充或修改协议</fullName>
            </value>
            <value>
                <fullName>未使用或修改艾伯维模板的采购协议</fullName>
            </value>
            <value>
                <fullName>工作说明书(SOW)</fullName>
            </value>
            <value>
                <fullName>Local Review</fullName>
            </value>
            <value>
                <fullName>Global Review</fullName>
            </value>
            <value>
                <fullName>保密协议</fullName>
            </value>
            <value>
                <fullName>捐赠协议</fullName>
            </value>
            <value>
                <fullName>赞助协议</fullName>
            </value>
            <value>
                <fullName>参会协议</fullName>
            </value>
            <value>
                <fullName>研究资助协议</fullName>
            </value>
            <value>
                <fullName>员工劳动合同/劳务解除合同</fullName>
            </value>
            <value>
                <fullName>其他与政府合同</fullName>
            </value>
            <value>
                <fullName>其他与HR部门相关或发起的协议</fullName>
            </value>
            <value>
                <fullName>招标相关-标书</fullName>
            </value>
            <value>
                <fullName>招标相关-药品配送协议</fullName>
            </value>
            <value>
                <fullName>招标相关-中标服务费支付协议</fullName>
            </value>
            <value>
                <fullName>招标相关-采购合同</fullName>
            </value>
            <value>
                <fullName>经销商相关合作协议（使用公司模板）</fullName>
            </value>
            <value>
                <fullName>销售合同</fullName>
            </value>
            <value>
                <fullName>艾伯维分公司</fullName>
            </value>
            <value>
                <fullName>租赁式服务办公室</fullName>
            </value>
            <value>
                <fullName>质量保证协议</fullName>
            </value>
            <value>
                <fullName>药物警戒协议</fullName>
            </value>
            <value>
                <fullName>临床研究协议</fullName>
            </value>
            <value>
                <fullName>委托检验合同</fullName>
            </value>
            <value>
                <fullName>其他</fullName>
            </value>
            <value>
                <fullName>谈判协议，与政府相关协议</fullName>
            </value>
            <value>
                <fullName>药物经济学合同(供应商模板)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Company_Chop__c/fields/Files_Content__c.field-meta.xml
<CustomField>
    <fullName>Files_Content__c</fullName>
    <label>文件内容</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Files_Types__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>在职证明/薪资证明</fullName>
            </value>
            <value>
                <fullName>劳动手册/退工单</fullName>
            </value>
            <value>
                <fullName>税单/完税证明</fullName>
            </value>
            <value>
                <fullName>居住证申请文件</fullName>
            </value>
            <value>
                <fullName>外籍员工居留许可/工作签证申请文件</fullName>
            </value>
            <value>
                <fullName>员工社保/公积金相关文件</fullName>
            </value>
            <value>
                <fullName>ESPP相关文件</fullName>
            </value>
            <value>
                <fullName>公司信用卡申请</fullName>
            </value>
            <value>
                <fullName>公司税务相关文件</fullName>
            </value>
            <value>
                <fullName>询证函</fullName>
            </value>
            <value>
                <fullName>注册申请表</fullName>
            </value>
            <value>
                <fullName>注册申请资料封面</fullName>
            </value>
            <value>
                <fullName>公文、申请函、企业标准、COA</fullName>
            </value>
            <value>
                <fullName>自查表</fullName>
            </value>
            <value>
                <fullName>临床试验方案、临床试验总结报告</fullName>
            </value>
            <value>
                <fullName>经销商授权书</fullName>
            </value>
            <value>
                <fullName>配送委托书</fullName>
            </value>
            <value>
                <fullName>招投标文件</fullName>
            </value>
            <value>
                <fullName>价格相关文件</fullName>
            </value>
            <value>
                <fullName>产品资料</fullName>
            </value>
            <value>
                <fullName>法人委托书</fullName>
            </value>
            <value>
                <fullName>进药资料</fullName>
            </value>
            <value>
                <fullName>授权委托书</fullName>
            </value>
            <value>
                <fullName>律师函</fullName>
            </value>
            <value>
                <fullName>声明</fullName>
            </value>
            <value>
                <fullName>授权书</fullName>
            </value>
            <value>
                <fullName>准入/谈判相关申请函/沟通函/说明函</fullName>
            </value>
            <value>
                <fullName>其他需Legal审阅文件</fullName>
            </value>
            <value>
                <fullName>医疗器械年度自查报告</fullName>
            </value>
            <value>
                <fullName>医疗器械检查记录（日常监督检查、专项检查以及飞行检查等）</fullName>
            </value>
            <value>
                <fullName>医保药学协会入会申请表</fullName>
            </value>
            <value>
                <fullName>其他市场准入相关文件</fullName>
            </value>
            <value>
                <fullName>其他</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Company_Chop__c/fields/Files_Type__c.field-meta.xml
<CustomField>
    <fullName>Files_Type__c</fullName>
    <label>文件类型</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>证照</fullName>
            </value>
            <value>
                <fullName>合同</fullName>
            </value>
            <value>
                <fullName>其他</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Company_Chop__c/fields/Files_Types__c.field-meta.xml
<CustomField>
    <fullName>Files_Types__c</fullName>
    <label>文件大类</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>HR相关文件</fullName>
            </value>
            <value>
                <fullName>财务相关文件</fullName>
            </value>
            <value>
                <fullName>RA注册相关文件</fullName>
            </value>
            <value>
                <fullName>Trade相关招标资料</fullName>
            </value>
            <value>
                <fullName>BU相关文件</fullName>
            </value>
            <value>
                <fullName>Legal相关文件</fullName>
            </value>
            <value>
                <fullName>GSP相关文件</fullName>
            </value>
            <value>
                <fullName>市场准入相关文件</fullName>
            </value>
            <value>
                <fullName>报关相关文件</fullName>
            </value>
            <value>
                <fullName>临床研究相关文件</fullName>
            </value>
            <value>
                <fullName>VISA相关文件</fullName>
            </value>
            <value>
                <fullName>行政相关文件</fullName>
            </value>
            <value>
                <fullName>PA相关文件</fullName>
            </value>
            <value>
                <fullName>超过系统容量的超大文件</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Company_Chop__c/fields/Legal_Entity__c.field-meta.xml
<CustomField>
    <fullName>Legal_Entity__c</fullName>
    <label>法律实体</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>艾伯维医药贸易(上海)有限公司</fullName>
            </value>
            <value>
                <fullName>北京分公司</fullName>
            </value>
            <value>
                <fullName>广州分公司</fullName>
            </value>
            <value>
                <fullName>杭州分公司</fullName>
            </value>
            <value>
                <fullName>成都分公司</fullName>
            </value>
            <value>
                <fullName>静安分公司</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CompanyChopHandler.cls
/**************************************************************************************************
 * Name: CompanyChopHandler
 * Object: Company_Chop__c
 * Purpose: CompanyChopTrigger handler
 * Author_Date: zhou 2019-10-18
***************************************************************************************************/
public with sharing class CompanyChopHandler{

    public static Company_Chop__c setApprover(Company_Chop__c chop)
    {
        //证照文件类型
        if(chop.Files_Type__c == '证照')
        {
            chop.Approver1__c = ApproverCandidates.getDepHead(chop.OwnerId,3)[0]; //Dep. Head
            if(chop.Legal_Entity__c == '艾伯维医药贸易(上海)有限公司')
            {
                if(chop.Certification_Doc__c == '进口药品注册证'){
                    chop.Approver2__c = null; //Lv Qi
                }
                if(chop.Certification_Doc__c == '法人身份证' || chop.Certification_Doc__c == '回乡证'){
                    chop.Approver2__c = null; //Tony Au
                }
            }
            if(chop.Legal_Entity__c == '北京分公司')
            {
                if(chop.Certification_Doc__c == '法人身份证'){
                    chop.Approver2__c = null; //Cheery Chen
                }
            }
            if(chop.Legal_Entity__c == '广州分公司')
            {
                if(chop.Certification_Doc__c == '法人身份证'){
                    chop.Approver2__c = null; //Luo Xuemei
                }
            }
            if(chop.Legal_Entity__c == '杭州分公司')
            {
                if(chop.Certification_Doc__c == '法人身份证'){
                    chop.Approver2__c = null; //Yu Peng
                }
            }
            if(chop.Legal_Entity__c == '成都分公司')
            {
                if(chop.Certification_Doc__c == '法人身份证'){
                    chop.Approver2__c = null; //Huang Haikuo
                }
            }
            if(chop.Legal_Entity__c == '静安分公司')
            {
                if(chop.Certification_Doc__c == '法人身份证'){
                    chop.Approver2__c = null; //Jeslin Wang
                }
            }
        }
        
        //合同类型
        if(chop.Files_Type__c == '合同')
        {
            chop.Approver3__c = null; //FD
            if(chop.Contract_Type__c == '采购相关协议')
            {
                chop.Approver2__c = null; //Starry
            }
            if(chop.Contract_Type__c == '临床研究相关协议')
            {	
                chop.Approver2__c = ApproverCandidates.getDepHead(chop.OwnerId,3)[0];//Dep. Head
                if(chop.Contract_Types__c == 'Global Review'){
                    chop.Approver1__c = ApproverCandidates.getDepHead(chop.OwnerId,3)[0];//Dep. Head
                }
            }
            if(chop.Contract_Type__c == 'OEC相关协议')
            {
                chop.Approver2__c = ApproverCandidates.getDepHead(chop.OwnerId,4)[0]; //BUD
            }
            if(chop.Contract_Type__c == 'HR相关协议')
            {
                chop.Approver1__c = ApproverCandidates.getDepHead(chop.OwnerId,4)[0]; //HRD
                if(chop.Contract_Types__c == '其他与政府合同' || chop.Contract_Types__c == '其他与HR部门相关或发起的协议'){
                    chop.Approver2__c = ApproverCandidates.getDepHead(chop.OwnerId,2)[0]; //HRD
                }
            }
            if(chop.Contract_Type__c == 'HIV招标相关协议')
            {
                chop.Approver2__c = ApproverCandidates.getDepHead(chop.OwnerId,4)[0]; //BUD
            }
            if(chop.Contract_Type__c == '商务部相关协议')
            {
                chop.Approver1__c = null; //Wayne Lu
            }
            if(chop.Contract_Type__c == '办公室租赁协议')
            {
                chop.Approver2__c = null; //Starry
            }
            if(chop.Contract_Type__c == '质量部相关协议')
            {
                chop.Approver1__c = ApproverCandidates.getLineManager(chop.OwnerId); //Line Mgr
            }
            if(chop.Contract_Type__c == '医学相关协议')
            {
                chop.Approver2__c = ApproverCandidates.getDepHead(chop.OwnerId,4)[0]; //BUD
            }
            if(chop.Contract_Type__c == '注册部相关协议')
            {
                if(chop.Contract_Types__c == '委托检验合同'){
                    chop.Approver1__c = null; //Cheery Chen
                }
            }
            if(chop.Contract_Type__c == 'MA')
            {
                chop.Approver2__c = ApproverCandidates.getDepHead(chop.OwnerId,3)[0]; //Dep. Head
            }
        }
        
        //其他类型
        if(chop.Files_Type__c == '其他')
        {
            chop.Approver3__c = null; //FD
            chop.Approver4__c = null; //Admin
            if(chop.Files_Types__c == 'HR相关文件')
            {
                chop.Approver1__c = ApproverCandidates.getQueueUsers('HR')[0]; //HR
                if(chop.Files_Content__c == '其他'){
                    chop.Approver1__c = null; //Elaine Lu
                }
            }
            if(chop.Files_Types__c == '财务相关文件')
            {
                if(chop.Files_Content__c == '公司信用卡申请'){
                    chop.Approver1__c = ApproverCandidates.getLineManager(chop.OwnerId); //Line Mgr
                }else{
                    chop.Approver1__c = null; //Teresa Liang
                }
            }
            if(chop.Files_Types__c == 'RA注册相关文件')
            {
                if(chop.Files_Content__c == '注册申请表' || chop.Files_Content__c == '其他'){
                    chop.Approver1__c = null; //Cheery Chen
                }else{
                    chop.Approver1__c = ApproverCandidates.getLineManager(chop.OwnerId); //Line Mgr
                }
            }
            if(chop.Files_Types__c == 'Trade相关招标资料')
            {
                chop.Approver1__c = ApproverCandidates.getLineManager(chop.OwnerId); //Line Mgr
                chop.Approver2__c = null; //Wayne Lu
            }
            if(chop.Files_Types__c == 'BU相关文件')
            {   
                if(chop.Files_Content__c == '进药资料'){
                    chop.Approver2__c = ApproverCandidates.getDepHead(chop.OwnerId,4)[0]; //BUD
                }
                if(chop.Files_Content__c == '授权委托书'){
                    chop.Approver1__c = ApproverCandidates.getLineManager(chop.OwnerId); //Line Mgr
                    chop.Approver2__c = ApproverCandidates.getDepHead(chop.OwnerId,4)[0]; //BUD
                }
            }
            if(chop.Files_Types__c == 'Legal相关文件')
            {
                chop.Approver1__c = ApproverCandidates.getLineManager(chop.OwnerId); //Line Mgr
                chop.Approver2__c = ApproverCandidates.getQueueUsers('Legal')[0]; //Legal
            }
            if(chop.Files_Types__c == 'GSP相关文件')
            {
                chop.Approver1__c = ApproverCandidates.getLineManager(chop.OwnerId); //Line Mgr
                chop.Approver2__c = null; //Li Bing
            }
            if(chop.Files_Types__c == '市场准入相关文件')
            {   
                if(chop.Files_Content__c == '医保药学协会入会申请表'){
                    chop.Approver1__c = ApproverCandidates.getLineManager(chop.OwnerId); //Line Mgr
                    chop.Approver2__c = null; //Lily Chen
                }
                else if(chop.Files_Content__c == '其他市场准入相关文件'){
                    chop.Approver1__c = null; //Lily Chen
                }else{
                    chop.Approver1__c = null; //Li Yi
                    chop.Approver2__c = null; //Lily Chen
                }
            }
            if(chop.Files_Types__c == '报关相关文件')
            {
                chop.Approver1__c = ApproverCandidates.getLineManager(chop.OwnerId); //Line Mgr
                chop.Approver2__c = ApproverCandidates.getQueueUsers('GTC')[0]; //GTC
            }
            if(chop.Files_Types__c == '临床研究相关文件')
            {
                if(chop.Files_Content__c == '其他'){
                    chop.Approver1__c = null; //Rachel Tang
                }else{
                    chop.Approver1__c = ApproverCandidates.getLineManager(chop.OwnerId); //Line Mgr
                }
            }
            if(chop.Files_Types__c == 'VISA相关文件')
            {
                chop.Approver1__c = ApproverCandidates.getDepHead(chop.OwnerId,3)[0]; //Dep. Head
            }
            if(chop.Files_Types__c == '行政相关文件')
            {
                chop.Approver1__c = ApproverCandidates.getLineManager(chop.OwnerId);//Line Mgr
            }
            if(chop.Files_Types__c == 'PA相关文件')
            {
                chop.Approver1__c = ApproverCandidates.getLineManager(chop.OwnerId);//Line Mgr
                chop.Approver2__c = null; //Vivian Wang
            }
            if(chop.Files_Types__c == '超过系统容量的超大文件')
            {
                chop.Approver1__c = ApproverCandidates.getDepHead(chop.OwnerId,3)[0]; //Dep. Head
            }
        }
    return chop;
    }
}