force-app/main/default/objects/CustomContract__c/CustomContract__c.object-meta.xml
<CustomObject>
    <label>合同</label>
    <nameField>
        <label>合同名称</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CustomContract__c/fields/ApplyUser__c.field-meta.xml
<CustomField>
    <fullName>ApplyUser__c</fullName>
    <label>申请人（组件用）</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CustomContract__c/fields/ApplyUsers__c.field-meta.xml
<CustomField>
    <fullName>ApplyUsers__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>申请人</label>
    <referenceTo>User</referenceTo>
    <relationshipName>CustomContracts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CustomContract__c/fields/ContractAmountType__c.field-meta.xml
<CustomField>
    <fullName>ContractAmountType__c</fullName>
    <label>合同金额分类</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>合同金额 &lt;= RMB 300,000</fullName>
            </value>
            <value>
                <fullName>RMB 300,000 &lt;= 合同金额 &lt;= RMB 1,000,000</fullName>
            </value>
            <value>
                <fullName>合同金额 &gt; 1,000,000</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CustomContract__c/fields/RequestDate__c.field-meta.xml
<CustomField>
    <fullName>RequestDate__c</fullName>
    <defaultValue>TODAY()</defaultValue>
    <label>申请日期</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/CustomContract__c/fields/RequestDepartment__c.field-meta.xml
<CustomField>
    <fullName>RequestDepartment__c</fullName>
    <label>申请部门</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/NewContracController.cls
/**************************************************************************************************
 * Name: NewContracController
 * Object: CustomContract
 * Author: zhou
 * Create Date: 2019-9-9
***************************************************************************************************/
public class NewContracController{

    @AuraEnabled
    public Static CustomContract__c doInit(){
      CustomContract__c rcd = new CustomContract__c();
      rcd.ApplyUser__c = Userinfo.getFirstName()+' '+Userinfo.getLastName();
      rcd.ApplyUsers__c = Userinfo.getUserId();
      rcd.RequestDate__c = Date.today();
      rcd.RequestDepartment__c = [SELECT Id,Department FROM User WHERE Id =:Userinfo.getUserId()].Department;
      return rcd;
    }   

  	@AuraEnabled
    public Static String saveMethd(String contracts){
        CustomContract__c item = (CustomContract__c)JSON.deserialize(contracts, CustomContract__c.class);
        if(item.ContractAmountType__c == '1') item.ContractAmountType__c = '合同金额 <= RMB 300,000';
        if(item.ContractAmountType__c == '2') item.ContractAmountType__c = 'RMB 300,000 <= 合同金额 <= RMB 1,000,000';
        if(item.ContractAmountType__c == '3') item.ContractAmountType__c = '合同金额 > 1,000,000';
        try{
        	Database.insert(item);
        	return item.Id;
        }catch(Exception e){System.debug(e.getMessage());}
        return Null;
    }  
}